[package]
name = "bad-spaceship-client"
version = "0.1.0"
authors = ["Sam Carey <sam@samcarey.com>"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.8", default-features = false }
bevy_rapier3d = "0.16"
serde = { version = "1.0", features = ["derive"] }
nalgebra = "0.31"
log = "0.4"
winit = { version = "0.26" }
gloo = { version = "0.7", optional = true }
web-sys = { version = "0.3.40", optional = true }
bevy_web_fullscreen = { git = "https://github.com/samcarey/bevy_web_fullscreen.git", branch = "master", optional = true }
bevy_egui = "0.15"
bad-spaceship-shared = { path = "../shared" }
shadow-rs = { version = "0.11", default-features = false }
rand = "0.8"
wasm-bindgen = "=0.2.83"

once_cell = "1.8"

[features]
default = [
    "bevy/bevy_gltf",
    "bevy/bevy_winit",
    "bevy/render",
    "bevy/bevy_core_pipeline",
]

native = [
    "bevy_rapier3d/simd-stable",
    "bevy_rapier3d/parallel",
    "bevy/bevy_gilrs",
]

web = ["web-sys", "gloo", "bevy_web_fullscreen"]

[build-dependencies]
shadow-rs = { version = "0.8", default-features = false }
