image: python:3.8-buster

pages:
  stage: deploy
  script:
    - pip install -r requirements.txt
    - mkdocs build --strict --verbose --site-dir public --config-file mkdocs.yml
  artifacts:
    paths:
      - public
  only:
    - master
  rules:
    - changes:
      - mkdocs.yml
      - docs/*

