image: samcarey/nobo.games-docker-ci

pages:
  stage: deploy
  script:
    - ls
    # - cd bevy && cargo make build-web
    - cd bevy
    - cd ..
    - ls
    - cd ~ && ls && mkdocs build --strict --verbose --site-dir public --config-file mkdocs.yml
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "ci"'
      # changes:
      # - mkdocs.yml
      # - docs/*

