[package]
name = "bad-spaceship-server"
version = "0.1.0"
authors = ["Sam Carey <sam@samcarey.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bad-spaceship-shared = { path = "../shared" }
bevy = { version = "0.15", default-features = false }
bevy_rapier3d = "0.28"

[features]
default = [
    "bevy_rapier3d/simd-stable",
    "bevy_rapier3d/parallel",
    # Hot-reload of RON config assets (watch_for_changes). The file watcher needs
    # the `multi_threaded` feature on to function.
    "bevy/file_watcher",
    "bevy/multi_threaded",
]
