[package]
name = "bad-spaceship-bevy"
version = "0.1.7"
authors = ["Sam Carey <sam@samcarey.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = {version="0.4.0", default-features=false}
bevy_rapier3d = { version = "0.8.0" }
serde = { version = "1.0.123", features = ["derive"] }
ron = "0.6.4"
nalgebra = "0.24.1"
rapier3d = "0.5.0"
# bevy_networking_turbulence = {git = "https://github.com/smokku/bevy_networking_turbulence", rev="1bfe6f44397e510009a8a80abad1e105d875bf94"}
log = "0.4"
rand = "0.8.3"
bevy_webgl2 = {version="0.4.2", optional = true}
include_dir = {version="0.6.0", optional = true}
winit = {version = "0.24.0", optional = true}
gloo = {version = "0.2.1", optional = true}
web-sys = {version = "0.3.4", optional = true}


[profile.dev]
opt-level = 3
debug = 0

[features]
default = [
  "bevy_rapier3d/simd-stable"
]

native = [
  "bevy/bevy_winit",
  "bevy/render",
  "bevy/bevy_wgpu",
  "bevy/bevy_gltf",
  "bevy_rapier3d/parallel",
]

web = [
  "bevy_webgl2",
  "include_dir",
  "web-sys",
  "gloo"
]
