[package]
name = "bad-spaceship-bevy"
version = "0.1.0"
authors = ["Sam Carey <sam@samcarey.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# External
bevy = "0.3.0"
serde = { version = "1.0.118", features = ["derive"] }
ron = "0.6.2"
nalgebra = "0.23.1"
bevy_rapier3d = { version = "0.6.2", features = ["simd-stable", "parallel"] }
rapier3d = "0.4.2"

# Internal
config_from_file_macro = { path = "crates/config_from_file_macro" }
config_from_file_macro_derive = { path = "crates/config_from_file_macro/config_from_file_macro_derive" }

[profile.dev]
opt-level = 0
debug = 2
