[package]
name = "bad-spaceship-bevy"
version = "0.1.0"
authors = ["Sam Carey <sam@samcarey.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# External
bevy = "0.3.0"
serde = { version = "1.0.118", features = ["derive"] }
ron = "0.6.2"
nalgebra = "0.23.1"
bevy_rapier3d = { version = "0.6.2", features = ["simd-stable", "parallel"] }
rapier3d = "0.4.2"
bevy_networking_turbulence = {git = "https://github.com/smokku/bevy_networking_turbulence", rev="ef0dd468c4cbacd2511f4855c7887391b045b4d2"}
simple_logger = "1"
rand = "0.7"
log = "0.4"
cfg-if = "1.0.0"

# Internal
config_from_file_macro = { path = "crates/config_from_file_macro" }
config_from_file_macro_derive = { path = "crates/config_from_file_macro/config_from_file_macro_derive" }

[profile.dev]
opt-level = 0
debug = 2
