[package]
name = "bad-spaceship-shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.5.0", default-features = false }
bevy_rapier3d = "0.11.0"
serde = { version = "1.0.126", features = ["derive"] }
ron = "0.7.0"
rand = "0.8.4"
include_dir = { version = "0.7" }
anyhow = "1.0"
bevy_easings = "0.4.1"

[features]
default = ["bevy/png"]
