//! Multiplayer networking protocol (lightyear).
//!
//! This module defines the *protocol* — the components, channels, and input
//! types the client and server agree on. It deliberately does NOT add
//! lightyear's `ClientPlugins` / `ServerPlugins`: those live in the client and
//! server crates respectively, and lightyear requires the protocol to be
//! registered *after* the relevant plugin group. `ProtocolPlugin` is added by
//! both binaries after their plugin group.
//!
//! Scaffold status: this registers a representative component + channel and
//! defines the per-tick input type, proving the lightyear 0.28 dependency builds
//! into every target (native + wasm). Wiring the live connection, replicating
//! the Avian physics bodies (via `lightyear_avian3d`), and client-side
//! prediction/interpolation come next, where they can be tested on real
//! endpoints.
use core::time::Duration;
use core::sync::atomic::{AtomicU32, Ordering};

// `ForcesItem` (the `Forces` query-data item the held-part spring writes through) is
// not re-exported in avian's prelude — reach it by its full module path.
use avian3d::dynamics::rigid_body::forces::ForcesItem;
use avian3d::prelude::{
    AngularVelocity, LinearVelocity, Position, ReadRigidBodyForces, Rotation, WriteRigidBodyForces,
};
use bevy::ecs::entity::{EntityMapper, MapEntities};
use bevy::prelude::*;
use lightyear::prelude::input::native::ActionState;
use lightyear::prelude::*;
use lightyear_avian3d::types::{angular_velocity, linear_velocity, position, rotation};
use serde::{Deserialize, Serialize};

use crate::utils::QuatExt;
use crate::{DirectionalInput, Yaw};

// Build-time version identity (generated by build.rs). `BS_PROTOCOL_ID` is fed
// into the netcode handshake on both ends so a cross-version client/server pair is
// rejected; `BS_VERSION` is the short git SHA. Both are re-exported here so the
// client and server crates reach them as `bad_spaceship_shared::net::BS_*`.
include!(concat!(env!("OUT_DIR"), "/bs_version.rs"));

/// The simulation tick interval (60 Hz). The client and server must agree on
/// this, so it lives in the shared protocol — both pass it to their lightyear
/// plugin group's `tick_duration`.
pub const TICK: Duration = Duration::from_millis(1000 / 60);

/// Identifies which connected client controls a replicated player entity.
#[derive(Component, Serialize, Deserialize, Clone, Copy, PartialEq, Debug)]
pub struct NetPlayer {
    pub client_id: u64,
    /// Which of the client's monster models this player wears (assigned by the
    /// server from the persistent resume id via `monster_index`, so it
    /// survives reload/reset and every client renders the same one).
    pub monster: u8,
}

/// How many monster models the client ships (`client/src/monster.rs`, which
/// compile-time asserts its table length against this).
pub const MONSTER_COUNT: u8 = 8;

/// One splitmix64 step: advances `state` and returns a well-mixed u64. THE
/// deterministic random primitive for everything derived from replicated
/// seeds (monster assignment, part metal looks): hand-rolled because the
/// derivation must be identical across platforms and versions — every client
/// (wasm + native) must derive the same result from the same seed, and `rand`
/// guarantees neither cross-version nor cross-platform stability for its
/// small RNGs.
pub fn splitmix64(state: &mut u64) -> u64 {
    *state = state.wrapping_add(0x9E37_79B9_7F4A_7C15);
    let mut z = *state;
    z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
    z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
    z ^ (z >> 31)
}

/// Deterministically assign a monster from a player's persistent id. Used by
/// the server (resume id from the connect token) AND the single-player client
/// (the same resume id read locally), so a given browser is the same monster
/// everywhere.
pub fn monster_index(id: u64) -> u8 {
    let mut state = id;
    (splitmix64(&mut state) % MONSTER_COUNT as u64) as u8
}

/// Pack a lobby code into the fixed 6-byte field the server keys rooms by
/// ([`NetInput::room`]): the matchmaker hands out 6 uppercase chars, so
/// uppercase, take up to 6 bytes, zero-pad. An empty code maps to all-zero —
/// the shared default room. Lives beside the wire format it defines so every
/// client of the protocol (the game client, the headless bot) packs rooms
/// identically.
pub fn room_code_bytes(code: &str) -> [u8; 6] {
    let mut out = [0u8; 6];
    for (slot, byte) in out.iter_mut().zip(code.to_ascii_uppercase().bytes()) {
        *slot = byte;
    }
    out
}

/// Pack a persistent resume id into a netcode connect-token `user_data` block
/// (little-endian u64 at offset 0), and read it back out. The one definition of
/// the wire layout shared by every writer (game client, headless bot) and the
/// server's connect-time reader — change it here or nowhere.
pub fn resume_user_data(resume_id: u64) -> [u8; 256] {
    let mut out = [0u8; 256];
    out[..8].copy_from_slice(&resume_id.to_le_bytes());
    out
}

/// See [`resume_user_data`].
pub fn resume_id_from_user_data(user_data: &[u8; 256]) -> u64 {
    u64::from_le_bytes(user_data[..8].try_into().unwrap())
}

/// Per-tick client → server **input intent** (not pose). The server runs the
/// authoritative character simulation from this intent (move direction, jump,
/// look angle), so the world is server-authoritative and — once client-side
/// prediction lands — the client predicts the same simulation locally and the
/// server reconciles only on divergence. The grab-ray fields are still sent from
/// the client's camera for now (the server's grab uses them directly); a later
/// phase reconstructs the ray from the simulated character + look angles.
///
/// Sent via lightyear's native-input channel (registered with
/// `InputPlugin::<NetInput>` in `ProtocolPlugin`); native inputs must be
/// `Serialize`/`Deserialize`/`Clone`/`PartialEq`/`Debug`/`Default` + `Reflect` +
/// `MapEntities`.
#[derive(Serialize, Deserialize, Clone, Copy, PartialEq, Debug, Default, Reflect)]
pub struct NetInput {
    /// Look-relative move intent: `[strafe(+right), forward]`, clamped to length 1
    /// (analog magnitude preserved for the touch joystick / gamepad).
    pub move_xz: [f32; 2],
    /// Jump intent this tick.
    pub jump: bool,
    /// Absolute look yaw (radians) — the movement basis and the avatar's facing.
    pub yaw: f32,
    /// Absolute look pitch (radians) — used by the server grab-ray reconstruction
    /// in a later phase (forwarded now to stabilise the protocol).
    pub pitch: f32,
    /// Camera-orbit-center world position — the origin of the grab look-ray.
    pub grab_origin: [f32; 3],
    /// Hold-point world position — where a grabbed part floats to.
    pub hold_target: [f32; 3],
    /// Target orientation for a held part (the orbit-center look basis, plus any
    /// rotate-gesture adjustment), so the held part doesn't tumble.
    pub hold_rotation: [f32; 4],
    /// The client's intent to be holding a part.
    pub grab: bool,
    /// One-shot intent to attach (joint) the held part to whatever it's touching.
    pub attach: bool,
    /// One-shot intent to delete a joint inside the delete zone (the empty-handed
    /// modifier-click gesture). The server finds the joint within `DELETE_RADIUS`
    /// of `hold_target` in the player's room and despawns it — mirroring `attach`.
    pub delete: bool,
    /// The lobby room code the client is in (the 6-char matchmaker code as raw
    /// bytes, zero-padded; all-zero = no code / default room). Constant for the
    /// session — carried on the already-reliable input channel rather than a
    /// separate connect message, so the server learns each client's room from its
    /// first input and scopes that client's world to it.
    pub room: [u8; 6],
    /// A stable per-player id the client persists in `localStorage` and re-sends on
    /// every connect (constant for the session, like `room`). After an iOS tab-
    /// suspension the page must reload — the wasm loop can't be revived in place — so
    /// the server remembers each player's last position keyed by this id and restores
    /// it when the same id reconnects within a grace window (server-authoritative
    /// session resume). An app-level token, NOT the netcode `client_id`, so a quick
    /// reconnect isn't rejected as a duplicate connection. `0` = no resume (native).
    pub resume_id: u64,
}

// Focus range / look-angle and the held-part spring stiffnesses are defined once
// in `part.rs` (the single-player gameplay tunables) and reused here so the
// multiplayer selection/hold matches single-player exactly.
use crate::part::{
    MAX_INTERACT_ANGLE, MAX_INTERACT_DISTANCE, ORIENTING_STIFFNESS, POSITIONING_STIFFNESS,
};

/// The part the player is most directly looking at (smallest look-angle within
/// range) — the same focus rule as single-player. `look` is the grab ray
/// direction (hold_target − grab_origin). `parts` yields `(entity,
/// world_position)`.
pub fn focused_part(
    origin: Vec3,
    look: Vec3,
    parts: impl Iterator<Item = (Entity, Vec3)>,
) -> Option<Entity> {
    let mut best = None;
    let mut smallest_angle = MAX_INTERACT_ANGLE;
    for (entity, pos) in parts {
        let between = pos - origin;
        if between.length_squared() < MAX_INTERACT_DISTANCE * MAX_INTERACT_DISTANCE {
            let angle = look.angle_between(between);
            if angle < smallest_angle {
                smallest_angle = angle;
                best = Some(entity);
            }
        }
    }
    best
}

/// Hold targets farther than this from the held part are treated as stale and
/// ignored by [`apply_hold_spring`] (see the guard there). Comfortably above any
/// real hold distance (`MAX_INTERACT_DISTANCE` = 7.5 plus the hold-point offset),
/// comfortably below the km-scale jump of an origin rebase.
pub const STALE_HOLD_DISTANCE: f32 = 50.0;

/// Critically-damped positioning acceleration that floats a held part to the
/// hold point (matches `position_held_part`'s oscillator). The caller subtracts
/// gravity to cancel the part's weight.
pub fn hold_acceleration(displacement: Vec3, velocity: Vec3) -> Vec3 {
    let damping = 2.0 * POSITIONING_STIFFNESS.sqrt();
    displacement * POSITIONING_STIFFNESS - velocity * damping
}

/// Critically-damped angular acceleration that drives a held part toward its
/// target orientation (matches `orient_held_part`'s oscillator). `rotation_vector`
/// is the axis-angle error (axis · angle) between the target and current rotation.
pub fn orient_acceleration(rotation_vector: Vec3, angular_velocity: Vec3) -> Vec3 {
    let damping = 2.0 * ORIENTING_STIFFNESS.sqrt();
    rotation_vector * ORIENTING_STIFFNESS - angular_velocity * damping
}

/// Apply the held-part spring for one fixed tick through `forces`: float the part
/// toward `hold_target` (critically-damped anti-gravity, cancelling its weight) and
/// orient it toward `hold_rotation` (critically-damped; the unset all-zero seed quat
/// is skipped). Shared by the client's predicted hold (`predict_hold`) and the
/// server's authoritative hold (`server_hold`) so both ends simulate an identical
/// spring and diverge only by round-trip. `position`/`rotation` are the part's current
/// Avian pose read by the caller — NOT `Transform`, which lags within the fixed
/// schedule when `lightyear_avian` owns the Position→Transform sync. Mirrors
/// single-player's `position_held_part`/`orient_held_part` (the same critically-damped
/// math via `hold_acceleration`/`orient_acceleration`); the server can't run those
/// directly because it has no camera-rig `HoldPoint` entity (its target arrives over
/// the wire as a raw position), hence this entity-free formulation.
pub fn apply_hold_spring(
    forces: &mut ForcesItem,
    position: Vec3,
    rotation: Quat,
    hold_target: Vec3,
    hold_rotation: Quat,
    gravity: Vec3,
) {
    // Position: float to the hold point, cancelling the part's weight.
    let displacement = hold_target - position;
    // Stale-target guard: a real hold target is never more than a few meters from
    // the part (`MAX_INTERACT_DISTANCE` bounds the grab). A huge displacement means
    // the target was computed in a different coordinate frame — after an origin
    // rebase (`NetRoomFrame`), the holder's forwarded `hold_target` (and the
    // replicated `NetHold` observers spring toward) stays in the pre-rebase frame
    // for ~1 round trip. Springing a critically-damped oscillator across a km-scale
    // "error" would yeet the part; skipping leaves it in free-fall for a few ticks,
    // which the spring recovers from imperceptibly.
    if displacement.length_squared() > STALE_HOLD_DISTANCE * STALE_HOLD_DISTANCE {
        return;
    }
    let lin_vel = forces.linear_velocity();
    forces.apply_linear_acceleration(hold_acceleration(displacement, lin_vel) - gravity);
    // Orientation: drive toward the target (seeded at pickup + rotate gesture). Skip
    // the unset seed (the all-zero default quat is never a real rotation).
    if hold_rotation.length_squared() > 0.5 {
        let error = (hold_rotation * rotation.conjugate()).to_rotation_vector();
        let ang_vel = forces.angular_velocity();
        forces.apply_angular_acceleration(orient_acceleration(error, ang_vel));
    }
}

// No entities are referenced by `NetInput`, so the mapping is a no-op — but
// the trait is a required bound for native inputs.
impl MapEntities for NetInput {
    fn map_entities<M: EntityMapper>(&mut self, _entity_mapper: &mut M) {}
}

/// The replicated shape of a part — enough for a client to rebuild the collider and
/// render mesh. A cuboid carries its own half-extents; a rocket engine is fixed
/// geometry (the `ROCKET_*` constants in `part.rs`), so it needs no parameters. This
/// is the shape discriminant `NetPart` carries so rockets replicate like any part
/// (before this, `NetPart` was cuboid-only and rockets were single-player).
#[derive(Serialize, Deserialize, Clone, Copy, PartialEq, Debug)]
pub enum PartShape {
    /// A random box; `half_extents` are half the full extents (`Collider::cuboid`
    /// takes full extents = 2 × these).
    Cuboid { half_extents: [f32; 3] },
    /// A rocket engine: cylinder body + cone flare, built from the shared `ROCKET_*`
    /// geometry constants (no per-instance parameters).
    RocketEngine,
}

impl Default for PartShape {
    // A degenerate unit cuboid — only hit if a `NetPart` is ever default-constructed
    // before replication fills it; real parts always carry a concrete shape.
    fn default() -> Self {
        PartShape::Cuboid { half_extents: [0.5, 0.5, 0.5] }
    }
}

/// Replicated shape of a part (see [`PartShape`]) plus a stable cross-network id. The
/// shape lets a client rebuild the collider + render mesh; the part's live pose rides
/// on the predicted Avian `Position`/`Rotation`. `id` is the server part entity's bits
/// — a *stable* identity (replicated onto both the client's `Confirmed` and `Predicted`
/// copies) that lets the client match a replicated joint's endpoints (`NetJoint`) to the
/// local *predicted* part entities, without depending on lightyear's confirmed→predicted
/// entity mapping.
#[derive(Component, Serialize, Deserialize, Clone, Copy, PartialEq, Debug, Default)]
pub struct NetPart {
    pub shape: PartShape,
    pub id: u64,
    /// Appearance seed (see `PartSeed`): clients derive the part's metal look
    /// from it, so every client renders the same part identically. (Ignored for
    /// rockets, whose striped body material is fixed.)
    pub seed: u32,
}

/// A replicated joint between two parts. Carries enough to reconstruct the joint
/// as *real predicted physics* on each client: the stable ids (`NetPart::id`) of
/// the two bodies and their body-local (COM-relative) anchors, in the same order
/// the server's `SphericalJoint` uses (`body1`/`anchor1` ↔ `local_anchor1`). The
/// client looks up the matching *predicted* part entities by id and spawns a real
/// Avian `SphericalJoint` between them, so the assembly is held together by the
/// client's own simulation (and survives rollback) — not just rendered. Without
/// this the predicted parts are unconstrained locally and a lifted assembly sags
/// apart, corrected only by replication.
#[derive(Component, Serialize, Deserialize, Clone, Copy, PartialEq, Debug, Default)]
pub struct NetJoint {
    pub body1: u64,
    pub body2: u64,
    pub anchor1: [f32; 3],
    pub anchor2: [f32; 3],
}

/// A replicated **player-lock weld**: a joint pinning a player's avatar to a part it
/// was touching when the player pressed "Lock" (one per weld contact). Carries enough
/// for each client to rebuild the constraint as *real predicted physics* — the exact
/// counterpart of [`NetJoint`], but the first body is an **avatar** (resolved by its
/// [`NetPlayer::client_id`], since avatars have no `NetPart::id`) and the second a part
/// (by [`NetPart::id`]). Anchors are body-local (origin-relative), frozen at the
/// contact so the weld has zero rest error. Clients also *derive* each player's locked
/// state from these (a player is locked iff any `NetLockJoint` names them), which is
/// what gates the launch button on "everyone is attached to the assembly".
#[derive(Component, Serialize, Deserialize, Clone, Copy, PartialEq, Debug, Default)]
pub struct NetLockJoint {
    /// The locked player's [`NetPlayer::client_id`].
    pub player: u64,
    /// The welded part's [`NetPart::id`].
    pub part: u64,
    /// Anchor in the avatar's local frame (identity rotation — the body is
    /// rotation-locked — so this is just `contact − avatar position` at weld time).
    pub anchor_player: [f32; 3],
    /// Anchor in the part's local frame.
    pub anchor_part: [f32; 3],
}

/// Sentinel [`NetJoint`] endpoint id meaning "the ground" (the `Grass` bowl). The
/// ground is spawned locally on every peer by `MapPlugin` rather than replicated,
/// so it has no `NetPart::id`; each client resolves this sentinel to its own local
/// ground entity. Never collides with a real id: part ids are live `Entity` bits,
/// and `u64::MAX` is not a valid entity encoding.
pub const GROUND_JOINT_ID: u64 = u64::MAX;

/// Marks a replicated part as a member of its room's **largest assembly** — the biggest
/// set of parts joined together (directly or transitively) through joints. The server
/// recomputes the assembly whenever a joint is created or deleted and adds/removes this
/// marker as membership changes; it replicates to every client in the room. This is the
/// authoritative "which parts form the assembly" signal — clients derive the
/// centre-of-mass orb and combined thrust arrow from it locally, over the *predicted*
/// parts, so those visuals track the client's own simulation with no network-rate lag
/// (rather than the server streaming a COM position). Parts jointed only *through the
/// ground* never count, because the server never joints a part to the ground
/// (`server_attach` attaches to other `NetPart`s only), so the assembly graph is purely
/// part-to-part.
#[derive(Component, Serialize, Deserialize, Clone, Copy, PartialEq, Debug, Default)]
pub struct InLargestAssembly;

/// Replicated launch state for a room, authored by the server onto that room's
/// state entity (the same room-scoped entity that carries the room's [`NetRoomFrame`])
/// so every client in the room sees the same countdown. A player
/// touching the room's largest assembly can start a launch ([`RequestLaunch`]); the
/// server runs the countdown here and, at blastoff, cuts the assembly's ground joints
/// and fires its rockets. Clients read this to draw the `3 → 2 → 1 → Blastoff!` banner
/// and — once `launched` — to apply the same balanced thrust to their *predicted*
/// rockets (so the liftoff is smooth, not rollback-jittered).
#[derive(Component, Serialize, Deserialize, Clone, Copy, PartialEq, Debug, Default)]
pub struct NetLaunch {
    /// Seconds left in the countdown while counting down (`> 0`); `0` when idle or
    /// already launched. Derived from [`blastoff_tick`](Self::blastoff_tick) — a HUD
    /// readout only. Never gate physics on it.
    pub remaining: f32,
    /// Whether blastoff has happened and the rockets are firing. A *level*: it arrives
    /// ~1 RTT after the fact, so it is right for visuals (banner, camera, planet ring)
    /// and wrong for physics — see [`launched_at`](Self::launched_at).
    pub launched: bool,
    /// The tick blastoff fires on, scheduled when the countdown arms and replicated
    /// [`LAUNCH_COUNTDOWN_TICKS`] (188) ahead of it. This is what makes liftoff
    /// tick-exact on every peer:
    /// the countdown gives everyone the answer long before the moment, so the client
    /// starts its burn (and cuts its predicted ground joints) on the *same* tick as
    /// the server instead of reacting to `launched` arriving late. `None` for a room
    /// that has never launched this session, and for a world restored from a save
    /// already in flight (nothing to schedule — `launched` covers it).
    pub blastoff_tick: Option<u32>,
    /// Everything the server's guidance optimizer sampled this launch's ascent program
    /// from, so the predicted client rebuilds the *identical* program rather than
    /// re-planning from its own live state a few ticks later. Replicating only the
    /// chosen angle was not enough — see [`LaunchSeed`](crate::guidance::LaunchSeed) for
    /// the 1.2 mrad standing command error that left behind.
    pub plan: crate::guidance::LaunchSeed,
}

/// How many ticks the pre-blastoff countdown runs for. Rounded **up** so the scheduled
/// moment is never earlier than [`LAUNCH_COUNTDOWN_SECS`](crate::launch::LAUNCH_COUNTDOWN_SECS)
/// — a countdown that fires a hair late is invisible; one that fires early clips the
/// banner. (`TICK` is 16 ms, not exactly 1/60 s, so this is 188, not 180.)
pub const LAUNCH_COUNTDOWN_TICKS: i32 = {
    let tick_ms = TICK.as_millis() as i32;
    let countdown_ms = (crate::launch::LAUNCH_COUNTDOWN_SECS * 1000.0) as i32;
    (countdown_ms + tick_ms - 1) / tick_ms
};

impl NetLaunch {
    /// Whether the engines are firing **at `tick`** — the predicate every physics site
    /// must use, on the server and on each predicted client alike.
    ///
    /// The point is that this is a pure function of a tick and a value replicated
    /// [`LAUNCH_COUNTDOWN_TICKS`] in advance, so both peers answer identically without
    /// either waiting to be told.
    ///
    /// Reading the `launched` *level* instead is what made the client start its burn
    /// **late on every single flight**: the level is replicate-only (no `.predict()`), so
    /// nothing ever replayed the missed ticks. How late depends on the link — measured at
    /// 4 ticks on the campaign's setup (a fixed 0.1997 m/s velocity deficit, exactly 4 ×
    /// the 0.04995 m/s a tick of thrust adds, which is how the lag was first identified)
    /// and at 1–2 ticks over loopback, where it was still late every run and still
    /// varied. Rollback absorbed the transient over ~100 ticks; it should never have
    /// existed. Note the deficit is not the whole cost — the client also held its
    /// predicted ground clamps for those ticks (see `release_predicted_ground_joints`).
    ///
    /// The tick delta is a wrapping `i32` (lightyear's `Tick` is a wrapping `u32`), so
    /// this stays correct across the counter's wrap and while a rollback replays ticks
    /// older than the schedule.
    pub fn launched_at(&self, tick: Tick) -> bool {
        match self.blastoff_tick {
            Some(scheduled) => {
                let elapsed: i32 = tick - Tick(scheduled);
                elapsed >= 0
            }
            // No schedule: a world restored from a save that was already in flight (or a
            // peer that connected mid-flight). The replicated level is all there is, and
            // it is correct — the launch is long past, so there is no tick to be exact about.
            None => self.launched,
        }
    }
}

/// Replicated **floating-origin frame** of a room, authored by the server onto the
/// room's state entity (alongside [`NetLaunch`]). Rooms whose
/// assembly climbs far from the origin are periodically **rebased**: the server
/// subtracts the assembly's position AND mean velocity from every room entity (a
/// Galilean boost into a co-moving frame — physics is invariant under it), so the
/// solver and the renderer always work near the origin at small local velocities
/// instead of starving f32 precision at extreme altitude (the old hard ceilings:
/// ~33 km ridden / ~524 km unmanned). The accumulated frame is the bookkeeping:
///
/// - true position = `offset` + local position (offset integrates as
///   `offset += velocity * dt` each fixed tick — f64, exact for any flight);
/// - true velocity = `velocity` + local velocity.
///
/// Client duties on a frame change: move the local ground to `-offset` (the true
/// ground position in room-local coordinates — fixes rendering, predicted physics,
/// and the flame ground raycast in one move) and derive HUD altitude/speed from the
/// frame. The rebase itself is PREDICTED: the decision is a pure function of sim
/// state ([`rebase_room_frame`]) that the client evaluates on its predicted world at
/// the same tick as the server (`predict_room_rebase`), so the shifted confirmed
/// state matches the shifted predicted state and no rollback fires. A mispredicted
/// rebase tick (the anchor crossing the trigger within the sims' sub-mm disagreement
/// of a tick boundary) degrades to the old behaviour: one uniform rollback whose
/// correction slides the whole scene rigidly.
#[derive(Component, Serialize, Deserialize, Clone, Copy, PartialEq, Debug, Default)]
pub struct NetRoomFrame {
    /// Room-frame origin in true world coordinates (f64: it grows without bound).
    pub offset: [f64; 3],
    /// Room-frame velocity in true world coordinates (the co-moving boost).
    pub velocity: [f32; 3],
    /// The server tick `offset` was sampled at. The frame is a linear recurrence
    /// (`offset += velocity·TICK` every tick, exactly, in f64), so this is what lets a
    /// predicted client reconstruct the frame at *its* tick instead of consuming the
    /// replicated sample as-is — see [`Self::frame_at`].
    pub tick: u32,
}

impl NetRoomFrame {
    /// The frame `(offset, velocity)` advanced to `tick` — the server's recurrence
    /// (`offset += velocity·TICK` per tick) replayed from the replicated sample, exact
    /// in f64 because that is exactly how the server integrates it.
    ///
    /// Predicted physics MUST use this, not the raw replicated value and not the
    /// client's visual frame mirror: the raw sample is ~1 packet stale (at 200 m/s
    /// that is metres of `r` error in `gravity_at`/`drag_force` — a standing
    /// differential acceleration against the server measured at ~0.003 m/s², enough
    /// to saw through the position tolerance every ~8 s), and the visual mirror is
    /// render-frame state, so a rollback replay would read ONE value across every
    /// replayed tick while the server's frame advanced per tick.
    pub fn frame_at(&self, tick: Tick) -> (bevy::math::DVec3, Vec3) {
        let velocity = Vec3::from_array(self.velocity);
        // Wrapping i32 tick delta: negative while a rollback replays ticks older than
        // the sample, which extrapolates backward along the same recurrence.
        let dticks: i32 = tick - Tick(self.tick);
        let offset = bevy::math::DVec3::from_array(self.offset)
            + velocity.as_dvec3() * (f64::from(dticks) * TICK.as_secs_f64());
        (offset, velocity)
    }

    /// Whether the room is currently rebased away from the true origin. An active
    /// frame means the true ground is far away: the server drops the ground bit from
    /// the room's collision filters and the client moves its ground to `-offset`.
    pub fn is_active(&self) -> bool {
        self.offset != [0.0; 3] || self.velocity != [0.0; 3]
    }
}

/// Local drift of a room's assembly that triggers a floating-origin rebase.
pub const REBASE_TRIGGER_M: f32 = 2000.0;

/// True distance from the origin below which an active frame resets to exactly
/// zero (real coordinates, real ground). Half of [`REBASE_TRIGGER_M`], so the two
/// can't flap: right after a reset the local drift is under the trigger.
pub const REBASE_RESET_M: f64 = 1000.0;

/// Where a rebase parks the assembly above the local origin. Keeps the freshly
/// shifted content clear of the phantom ground collider (and of the client's
/// not-yet-moved local ground while the client applies the shift).
pub const REBASE_REST_Y: f32 = 100.0;

/// A rebase decision applied to a room frame: subtract `(dpos, dvel)` from every
/// room entity's position/velocity, and the frame becomes `(offset, velocity)`.
pub struct RebaseOutcome {
    pub dpos: Vec3,
    pub dvel: Vec3,
    pub offset: bevy::math::DVec3,
    pub velocity: Vec3,
}

/// The floating-origin rebase decision for one room, as a pure function of the
/// frame and the room's anchor (its largest assembly's volume-weighted mean
/// position/velocity): `Some` when the room rebases this tick, with the shift to
/// subtract from every room entity and the resulting frame.
///
/// This is THE single decision path — the server applies it authoritatively
/// (`rebase_room_frames`) and a predicted client mirrors it on its predicted world
/// at the same tick (`predict_room_rebase`), so the rebase never reaches the
/// rollback comparator as a surprise. Any fork in this logic is a guaranteed
/// rollback per rebase, so keep it here, shared.
///
/// The reset branch lands the frame *exactly* on zero (assignment, not
/// accumulation of the inverse shift — an f32 round trip would leave a residue and
/// the ground must become real again).
pub fn rebase_room_frame(
    offset: bevy::math::DVec3,
    velocity: Vec3,
    anchor_pos: Vec3,
    anchor_vel: Vec3,
) -> Option<RebaseOutcome> {
    let active = offset != bevy::math::DVec3::ZERO || velocity != Vec3::ZERO;
    let true_anchor = offset + anchor_pos.as_dvec3();
    if active && true_anchor.length() < REBASE_RESET_M {
        Some(RebaseOutcome {
            dpos: -offset.as_vec3(),
            dvel: -velocity,
            offset: bevy::math::DVec3::ZERO,
            velocity: Vec3::ZERO,
        })
    } else if anchor_pos.length() > REBASE_TRIGGER_M {
        let dpos = anchor_pos - Vec3::Y * REBASE_REST_Y;
        Some(RebaseOutcome {
            dpos,
            dvel: anchor_vel,
            offset: offset + dpos.as_dvec3(),
            velocity: velocity + anchor_vel,
        })
    } else {
        None
    }
}

/// The weighted mean position/velocity of a set of `(position, velocity, weight)`
/// samples — the rebase anchor arithmetic, shared so the server's authoritative
/// anchor and the client's predicted one ([`rebase_room_frame`]'s input) are the
/// same reduction and can't fork. `None` when the samples carry no weight.
/// (Iteration *order* still differs between the peers — ECS query order vs the
/// server's index arrays — which is ULP-scale noise, dwarfed by the sims' sub-mm
/// state drift.)
pub fn weighted_anchor(
    samples: impl Iterator<Item = (Vec3, Vec3, f32)>,
) -> Option<(Vec3, Vec3)> {
    let (mut weighted_pos, mut weighted_vel, mut mass) = (Vec3::ZERO, Vec3::ZERO, 0.0f32);
    for (position, velocity, weight) in samples {
        weighted_pos += position * weight;
        weighted_vel += velocity * weight;
        mass += weight;
    }
    (mass > 0.0).then(|| (weighted_pos / mass, weighted_vel / mass))
}

/// A part's volume — the mass proxy under uniform density (full cuboid volume, or the
/// rocket's precomputed cylinder+cone volume). Shared by the server's assembly COM,
/// the launch COM, and the client's predicted rebase anchor so all weigh parts
/// identically.
pub fn part_volume(shape: PartShape) -> f32 {
    match shape {
        PartShape::Cuboid { half_extents } => {
            let he = Vec3::from_array(half_extents);
            8.0 * he.x * he.y * he.z
        }
        PartShape::RocketEngine => crate::part::ROCKET_VOLUME,
    }
}

/// Replicated hold state for a part a player is currently holding: who holds it
/// (their [`NetPlayer::client_id`]) and the hold point + target orientation the server
/// is springing it toward (the holder's forwarded `hold_target`/`hold_rotation`). All
/// loose parts are predicted on *every* client (`PredictionTarget::All`), but only the
/// holder runs the hold spring locally — so without this a remote observer predicts the
/// held part in **free-fall** and replication yanks it back up every snapshot, making it
/// sag and bob for everyone except the holder. With it, each client springs the held
/// part toward this target with the same `apply_hold_spring` the server uses, so the
/// part floats smoothly for observers too. The holder ignores its own (it predicts with
/// its local, zero-delay hold point); the component is removed when the part is released.
#[derive(Component, Serialize, Deserialize, Clone, Copy, PartialEq, Debug, Default)]
pub struct NetHold {
    /// The holder's `NetPlayer::client_id`, so the holder's own client can skip it.
    pub holder: u64,
    /// Hold-point world position the part is sprung toward (the holder's `hold_target`).
    pub target: [f32; 3],
    /// Target orientation for the held part (the holder's `hold_rotation`).
    pub rotation: [f32; 4],
}

/// A player's display **name**, replicated to every client sharing the room so it
/// can be drawn as a billboard over the avatar's head and listed in the on-screen
/// roster. The server assigns a unique default (`"Player N"`, lowest free N within
/// the room) when the avatar joins its room (`assign_rooms`); the owning client can
/// rename it by sending a [`SetName`] message, which the server sanitises and writes
/// back here. Not `Copy` (owns a `String`), so — unlike the other replicated
/// components — it derives only `Clone`; replication clones it, which is all
/// `.replicate()` needs. No interpolation (a name is discrete, not eased).
#[derive(Component, Serialize, Deserialize, Clone, PartialEq, Debug, Default)]
pub struct NetName(pub String);

/// Client → server request to rename the sender's own avatar. The server resolves
/// the sender's avatar (via `ControlledBy`), [`sanitize_name`]s the string, and
/// writes it onto that avatar's [`NetName`] (from which it re-replicates to everyone
/// in the room). Sent on the reliable [`ControlChannel`] so a one-shot rename isn't
/// dropped.
#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct SetName(pub String);

/// Client → server request to change the sender's avatar (monster skin) to the given
/// index. The server resolves the sender's avatar (via `ControlledBy`), reduces the
/// index modulo [`MONSTER_COUNT`], and writes it onto that avatar's
/// [`NetPlayer::monster`] — from which it re-replicates to everyone in the room, so
/// every client re-dresses the avatar. Sent on the reliable [`ControlChannel`] so a
/// one-shot pick isn't dropped. The picker greys out avatars other players already
/// wear, but the server does not *enforce* uniqueness (assignment can already collide
/// by hash) — the choice is applied as sent.
#[derive(Serialize, Deserialize, Clone, Copy, PartialEq, Debug)]
pub struct SetAvatar(pub u8);

/// Client → server request to teleport the sender's avatar back to a fresh spawn
/// position (the "Reset Position" menu action — e.g. to recover after falling off or
/// getting stuck). Server-authoritative: the server moves the avatar's `Position` and
/// zeroes its velocity, from where the reset replicates/corrects on the owner. A unit
/// message on the reliable [`ControlChannel`].
#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct ResetPosition;

/// Client → server request to set the sender's **lock** state (the top-of-screen
/// "Lock"/"Unlock" button, shown while standing on the assembly). `true` welds the
/// sender's avatar to every part it is currently touching (one [`NetLockJoint`] weld
/// per contact, frozen in place); `false` dissolves all of the sender's lock welds.
/// Idempotent — locking while already locked (or unlocking while free) is a no-op, so
/// the reliable channel's occasional duplicate delivery is harmless. On the reliable
/// [`ControlChannel`] so a one-shot press isn't dropped.
#[derive(Serialize, Deserialize, Clone, Copy, PartialEq, Debug)]
pub struct SetLocked(pub bool);

/// Client → server request to start a rocket launch for the sender's room. The server
/// resolves the sender's room (via `ControlledBy` → the avatar's `RoomMember`) and, if
/// that room isn't already counting down or launched, starts its countdown (whose state
/// then replicates to every client in the room via [`NetLaunch`]). A unit message on the
/// reliable [`ControlChannel`] so the one-shot swipe isn't dropped. Gated client-side on
/// the player actually touching the room's largest assembly; the server trusts that gate
/// (any room member may launch — the launch is a room-wide event, not a per-player one).
#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct RequestLaunch;

/// Client → server request to reset the sender's **room** to its initial conditions:
/// the world the room started with (the loaded save, or the fresh spawn) is restored —
/// parts and joints back at their starting poses, the blastoff/countdown state cleared,
/// and every player in the room teleported to a fresh spawn. Room-wide (like a launch,
/// not a per-player action); the client gates it behind a confirmation dialog. A unit
/// message on the reliable [`ControlChannel`].
#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct ResetRoom;

/// Client → server request to save the sender's room world under a player-chosen name
/// (the in-game "Save Game" form — the manual counterpart of the server's rolling
/// autosave, written to a separate file the autosave never overwrites). The server
/// resolves the sender's room (via `ControlledBy` → the avatar's `RoomMember`),
/// [`sanitize_name`]s the string (same rules as a rename), and snapshots the room to
/// disk. On the reliable [`ControlChannel`] so a one-shot save isn't dropped.
#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct SaveGame(pub String);

/// Reliable client → server control channel for one-shot user actions ([`SetName`],
/// [`ResetPosition`], [`ResetRoom`], [`RequestLaunch`], [`SaveGame`]). Separate from the unreliable
/// [`TelemetryChannel`] because these are deliberate actions that must not be silently lost.
pub struct ControlChannel;

/// Cap on a display name's length (characters). The server truncates to this and the
/// client's edit field enforces it, so an over-long name can't bloat replication or
/// overflow the label.
pub const MAX_NAME_LEN: usize = 20;

/// Normalise a user-supplied display name: trim surrounding whitespace and cap to
/// [`MAX_NAME_LEN`] characters. Returns an empty string for an all-whitespace input,
/// which the caller treats as "no change" (so a blank rename never wipes a name).
/// Shared so the server and the client's edit field agree on the rules.
pub fn sanitize_name(raw: &str) -> String {
    raw.trim().chars().take(MAX_NAME_LEN).collect()
}

/// Whether an avatar's player is currently pressing a move or jump input, replicated
/// **server → other clients** purely so remote avatars animate honestly: the walk
/// animation plays only on real input, never from world-frame motion (a rider on a
/// laterally-drifting rocket is NOT running). Mirrored from each avatar's buffered
/// `NetInput` by the server (`sync_avatar_moving`, the `NetFacing` pattern); the
/// owner never reads it (its own animation keys off the local `DirectionalInput`
/// with zero delay). Predict-synced so it reaches the *predicted* remote avatars;
/// never triggers a rollback (cosmetic, not part of the physics sim).
#[derive(Component, Serialize, Deserialize, Clone, Copy, PartialEq, Debug, Default)]
pub struct NetMoving(pub bool);

fn moving_should_rollback(_confirmed: &NetMoving, _predicted: &NetMoving) -> bool {
    false
}

/// An avatar's look yaw (radians), replicated **server → other clients** purely so
/// remote avatars can be drawn facing the way they look. Deliberately a *separate*
/// component from the local-input [`Yaw`]: the owner drives its own `Yaw` locally
/// (the camera rig) and must NOT have it overwritten by the server's round-trip-
/// stale copy — replicating `Yaw` itself made the owner's turning jitter/snap back.
/// The server mirrors each avatar's `Yaw` into `NetFacing` (`sync_avatar_facing`);
/// the owner never reads `NetFacing`, so the round-trip copy landing on its
/// predicted entity is inert, while remote (interpolated) clients read it to face
/// the avatar (`face_replicated_players`).
#[derive(Component, Serialize, Deserialize, Clone, Copy, PartialEq, Debug, Default)]
pub struct NetFacing(pub f32);

/// Interpolate a replicated look yaw along the **shortest** angular path, so a
/// wrap across ±π eases smoothly instead of spinning the long way. Used by
/// lightyear's interpolation for remote avatars' `NetFacing` (their facing).
fn lerp_facing(start: NetFacing, other: NetFacing, t: f32) -> NetFacing {
    use core::f32::consts::{PI, TAU};
    let delta = (other.0 - start.0 + PI).rem_euclid(TAU) - PI;
    NetFacing(start.0 + delta * t)
}

/// Roll back on velocity divergence too, but only past a *meaningful* margin — NOT
/// the default exact `PartialEq` (which fires a rollback on a hair of float drift
/// almost every tick → re-sims the whole predicted world every frame → stutter on a
/// single-threaded phone), and NOT never (which lets velocity drift unbounded until
/// it surfaces as a delayed position snap — e.g. coasting to a stop then jumping
/// back, because the client and server decayed momentum slightly differently and
/// nothing re-synced the velocity).
///
/// Sizing (measured, PR #143): contact/constraint noise — dominated by clamped
/// assemblies whose joints and contacts resolve slightly differently on client and
/// server — routinely diverges by 0.3–2.4 m/s, so the old 0.5 m/s margin fired a
/// whole-world rollback ~14×/s **with everything at rest**. Each rollback re-sims
/// ~8 ticks; while the player walks, every replay re-resolves their ground contact
/// slightly differently, and the accumulated decimetre errors + their corrections
/// were the reported "dizzying" world shake. At 2.5 m/s the chronic trigger is
/// gone (measured: 13.6/s → 1.1/s while walking; camera jerk RMS −33%); genuine
/// divergence is still caught — a velocity error this size moves a body past the
/// position tolerance within a snapshot or two, and the position rollback restores
/// the full state, velocity included.
const LINEAR_VELOCITY_ROLLBACK_TOLERANCE: f32 = 2.5; // m/s
const ANGULAR_VELOCITY_ROLLBACK_TOLERANCE: f32 = 5.0; // rad/s

/// Euclidean divergence of two `Vec3`-newtype values past a tolerance — the shared
/// body of the per-component (position / linear-vel / angular-vel) rollback conditions.
fn over_tolerance(confirmed: Vec3, predicted: Vec3, tolerance: f32) -> bool {
    confirmed.distance_squared(predicted) > tolerance * tolerance
}

fn linear_velocity_should_rollback(confirmed: &LinearVelocity, predicted: &LinearVelocity) -> bool {
    let over = over_tolerance(confirmed.0, predicted.0, LINEAR_VELOCITY_ROLLBACK_TOLERANCE);
    if over {
        LINVEL_ROLLBACK_TRIGGERS.fetch_add(1, Ordering::Relaxed);
    }
    over
}

/// `NetFacing` must NEVER trigger a rollback: it's server-authored and cosmetic (not
/// part of the local physics sim), so a confirmed≠predicted difference should just
/// update the value, not re-simulate the world — and a remote player turning their
/// head changes it every tick. (It's predict-synced at all only so it reaches the
/// predicted remote avatar.)
fn facing_should_rollback(_confirmed: &NetFacing, _predicted: &NetFacing) -> bool {
    false
}

fn angular_velocity_should_rollback(
    confirmed: &AngularVelocity,
    predicted: &AngularVelocity,
) -> bool {
    let over = over_tolerance(confirmed.0, predicted.0, ANGULAR_VELOCITY_ROLLBACK_TOLERANCE);
    if over {
        ANGVEL_ROLLBACK_TRIGGERS.fetch_add(1, Ordering::Relaxed);
    }
    over
}

/// Only roll back the predicted pose when it diverges from the server's confirmed
/// pose by a *visible* margin — NOT lightyear's default exact `PartialEq`, which
/// fires a full-world rollback on sub-millimeter float drift. The client and server
/// run the same sim but not bit-identically (FP non-determinism across platforms),
/// so an exact check diverges almost every snapshot → a rollback (re-simming the
/// character + every predicted part) nearly every frame → the predicted character
/// and the camera mounted on it judder, reading as a low-frame-rate "roughness".
/// A few-cm / few-degree tolerance lets the client keep its locally-predicted pose
/// for trivial disagreements (still server-authoritative on real divergence — a
/// wall hit, a shove — which exceeds the margin and snaps, eased by visual
/// correction), so prediction stays smooth. Applies to every predicted body
/// (registration is global): the character *and* the loose parts.
/// Position sized with the velocity margin above (PR #143): 0.05 m is under one
/// tick of walk motion (~0.07 m at 4.2 m/s), so any tick-phase wobble while
/// walking fired chronic rollbacks; 0.10 m keeps a standing block visually honest
/// while letting ordinary walking prediction breathe.
const POSITION_ROLLBACK_TOLERANCE: f32 = 0.10; // metres
const ROTATION_ROLLBACK_TOLERANCE: f32 = 0.05; // radians (~3°)

/// Diagnostics for the determinism/lag work: the largest position divergence (mm)
/// that triggered a rollback and how many such triggers occurred, since the last
/// telemetry flush. Small maxima (~5-15cm) ⇒ movement/sync drift; large ones
/// (sub-metre→metres) ⇒ contact chaos (a shoved block resolving a tick apart). Read
/// + reset by `take_rollback_diag` (client telemetry); never updated on the server
/// (it doesn't roll back). Atomic because `position_should_rollback` is a free fn
/// lightyear calls with no access to a resource.
static MAX_POS_ERR_MM: AtomicU32 = AtomicU32::new(0);
static POS_ROLLBACK_TRIGGERS: AtomicU32 = AtomicU32::new(0);

/// Per-condition rollback trigger counts for the *non-position* conditions
/// (rotation / linear-vel / angular-vel). Position has its own diag above; a flight
/// rollback storm shows `trig=0` (position quiet) while `rb` is high, so the storm is
/// driven by one of these three — but until now they were unmeasured. Counting them
/// says *which* divergence axis drives the ride storm (rotation ringing, velocity
/// disagreement, or spin), which picks the fix. Same free-fn / atomic shape as the
/// position diag (the conditions are free fns lightyear calls with no resource access).
static ROT_ROLLBACK_TRIGGERS: AtomicU32 = AtomicU32::new(0);
static LINVEL_ROLLBACK_TRIGGERS: AtomicU32 = AtomicU32::new(0);
static ANGVEL_ROLLBACK_TRIGGERS: AtomicU32 = AtomicU32::new(0);
/// Largest rotation divergence (millidegrees) that triggered a rollback since the last
/// flush — sizes the rotation storm (is the ring a few degrees over the 3° tolerance,
/// or tens of degrees?), the rotation twin of `MAX_POS_ERR_MM`.
static MAX_ROT_ERR_MDEG: AtomicU32 = AtomicU32::new(0);

/// **Determinism floor.** The largest predicted-vs-confirmed divergence seen at ANY
/// rollback check — *regardless of tolerance* — plus how many checks were compared. On
/// a perfect single-player link a bit-deterministic sim would keep these at ~0; whatever
/// they read is the raw non-determinism the tolerances have been masking. `pos` in
/// micrometres, `rot` in microdegrees (fine enough to see float-ULP-scale drift).
static MAX_POS_DIVERGENCE_UM: AtomicU32 = AtomicU32::new(0);
static MAX_ROT_DIVERGENCE_UDEG: AtomicU32 = AtomicU32::new(0);
static DIVERGENCE_CHECKS: AtomicU32 = AtomicU32::new(0);

/// **Culprit sites.** The counters above say *how much* a rollback storm there is, but
/// lightyear calls the rollback conditions as free fns with no entity access, so they
/// have never said *which body* diverges — and that is the thing that names the fix.
/// Each trigger therefore records the *confirmed* value it fired on, and the client
/// matches those values back to entities (`tally_rollback_culprits`). The match is exact
/// rather than a nearest-neighbour guess, because the value recorded here IS the one the
/// condition was handed — see that function for where it has to be looked up, which is
/// NOT any live component.
///
/// Capped so a storm can't grow this without bound; the overflow count is reported so
/// a truncated window is never mistaken for a quiet one. Diagnostic-only (native).
#[cfg(not(target_arch = "wasm32"))]
static TRIGGER_SITES: std::sync::Mutex<TriggerSites> = std::sync::Mutex::new(TriggerSites {
    positions: Vec::new(),
    rotations: Vec::new(),
    dropped: 0,
});

/// The confirmed values that tripped a rollback this window — see [`TRIGGER_SITES`].
#[cfg(not(target_arch = "wasm32"))]
#[derive(Default)]
pub struct TriggerSites {
    /// Confirmed position, and the divergence (mm) that fired the trigger.
    pub positions: Vec<(Vec3, u32)>,
    /// Confirmed rotation, and the divergence (millidegrees) that fired the trigger.
    pub rotations: Vec<(Quat, u32)>,
    /// Triggers past [`MAX_TRIGGER_SITES`] that were not recorded.
    pub dropped: u32,
}

/// Per-window cap on recorded sites. A storm can fire thousands of times per window and
/// the tally only needs the shape, not every sample.
#[cfg(not(target_arch = "wasm32"))]
const MAX_TRIGGER_SITES: usize = 4096;

/// Record one trigger's confirmed value in the bucket `pick` selects, honouring the cap
/// and counting the overflow. `pick` runs twice (length check, then push), so it takes
/// `Fn` rather than `FnOnce`.
#[cfg(not(target_arch = "wasm32"))]
fn record_site<T>(value: T, err: u32, pick: impl Fn(&mut TriggerSites) -> &mut Vec<(T, u32)>) {
    let mut guard = TRIGGER_SITES.lock().unwrap_or_else(|e| e.into_inner());
    let sites = &mut *guard;
    if pick(sites).len() < MAX_TRIGGER_SITES {
        pick(sites).push((value, err));
    } else {
        sites.dropped += 1;
    }
}

/// Take and reset this window's rollback culprit sites. See [`TRIGGER_SITES`].
#[cfg(not(target_arch = "wasm32"))]
pub fn take_trigger_sites() -> TriggerSites {
    let mut sites = TRIGGER_SITES.lock().unwrap_or_else(|e| e.into_inner());
    core::mem::take(&mut *sites)
}

/// Take and reset the determinism-floor stats: `(max_pos_um, max_rot_udeg, checks)`.
pub fn take_divergence_floor() -> (u32, u32, u32) {
    (
        MAX_POS_DIVERGENCE_UM.swap(0, Ordering::Relaxed),
        MAX_ROT_DIVERGENCE_UDEG.swap(0, Ordering::Relaxed),
        DIVERGENCE_CHECKS.swap(0, Ordering::Relaxed),
    )
}

/// Take and reset the rollback-divergence diagnostics: `(max_pos_err_mm, triggers)`.
pub fn take_rollback_diag() -> (u32, u32) {
    (
        MAX_POS_ERR_MM.swap(0, Ordering::Relaxed),
        POS_ROLLBACK_TRIGGERS.swap(0, Ordering::Relaxed),
    )
}

/// Take and reset the per-condition non-position rollback trigger counts plus the
/// largest rotation divergence: `(rotation, linear_vel, angular_vel, max_rot_mdeg)`.
/// See the statics above.
pub fn take_condition_triggers() -> (u32, u32, u32, u32) {
    (
        ROT_ROLLBACK_TRIGGERS.swap(0, Ordering::Relaxed),
        LINVEL_ROLLBACK_TRIGGERS.swap(0, Ordering::Relaxed),
        ANGVEL_ROLLBACK_TRIGGERS.swap(0, Ordering::Relaxed),
        MAX_ROT_ERR_MDEG.swap(0, Ordering::Relaxed),
    )
}

fn position_should_rollback(confirmed: &Position, predicted: &Position) -> bool {
    // Determinism floor: record the raw divergence for EVERY check (µm), tolerance aside.
    let dist = confirmed.0.distance(predicted.0);
    MAX_POS_DIVERGENCE_UM.fetch_max((dist * 1_000_000.0) as u32, Ordering::Relaxed);
    DIVERGENCE_CHECKS.fetch_add(1, Ordering::Relaxed);
    let over = over_tolerance(confirmed.0, predicted.0, POSITION_ROLLBACK_TOLERANCE);
    if over {
        MAX_POS_ERR_MM.fetch_max((dist * 1000.0) as u32, Ordering::Relaxed);
        POS_ROLLBACK_TRIGGERS.fetch_add(1, Ordering::Relaxed);
        #[cfg(not(target_arch = "wasm32"))]
        record_site(confirmed.0, (dist * 1000.0) as u32, |sites| &mut sites.positions);
    }
    over
}

fn rotation_should_rollback(confirmed: &Rotation, predicted: &Rotation) -> bool {
    let angle = confirmed.0.angle_between(predicted.0);
    // Determinism floor: raw rotation divergence for every check (µdeg), tolerance aside.
    MAX_ROT_DIVERGENCE_UDEG.fetch_max((angle.to_degrees() * 1_000_000.0) as u32, Ordering::Relaxed);
    let over = angle > ROTATION_ROLLBACK_TOLERANCE;
    if over {
        ROT_ROLLBACK_TRIGGERS.fetch_add(1, Ordering::Relaxed);
        MAX_ROT_ERR_MDEG.fetch_max((angle.to_degrees() * 1000.0) as u32, Ordering::Relaxed);
        #[cfg(not(target_arch = "wasm32"))]
        record_site(confirmed.0, (angle.to_degrees() * 1000.0) as u32, |sites| {
            &mut sites.rotations
        });
    }
    over
}

// lightyear's `LerpFn` takes its endpoints by value; `lightyear_avian3d`'s lerps
// take them by reference, so wrap them.
fn position_lerp(start: Position, other: Position, t: f32) -> Position {
    // A step this large between two interpolation snapshots is a floating-origin
    // rebase (`NetRoomFrame`), not motion — every predicted entity snaps through
    // it in one frame, so an *interpolated* entity (a remote avatar) must too, or
    // it visibly streaks km across the scene over the interpolation window.
    const REBASE_SNAP_M: f32 = 500.0;
    if start.0.distance_squared(other.0) > REBASE_SNAP_M * REBASE_SNAP_M {
        return other;
    }
    position::lerp(&start, &other, t)
}
fn rotation_lerp(start: Rotation, other: Rotation, t: f32) -> Rotation {
    rotation::lerp(&start, &other, t)
}
fn linear_velocity_lerp(start: LinearVelocity, other: LinearVelocity, t: f32) -> LinearVelocity {
    linear_velocity::lerp(&start, &other, t)
}
fn angular_velocity_lerp(start: AngularVelocity, other: AngularVelocity, t: f32) -> AngularVelocity {
    angular_velocity::lerp(&start, &other, t)
}

/// Bridge a networked avatar's per-tick input *intent* into the movement inputs the
/// shared `walk_based_on_input`/`jump_based_on_input` read — `DirectionalInput`
/// (move + jump) and `Yaw` (look). Runs in `FixedUpdate` *before* `CharacterMovement`
/// on BOTH ends: the server simulates the body authoritatively from intent, and the
/// predicting client replays the same intent through the same systems so rollback
/// reconciles deterministically.
///
/// Deliberately does NOT touch the body's Avian `Rotation`. The body is
/// `ROTATION_LOCKED` and stays at identity, which is what the camera rig relies on:
/// the camera-orbit center is a *child* of the body and applies the full look yaw
/// itself (`mouse_motion`), so writing yaw onto the body too would double the
/// camera's rotation relative to the movement direction. Remote-player *facing* is
/// therefore carried separately (a replicated look angle applied to the rendered
/// avatar), not by spinning the physics body.
pub fn apply_net_input(
    mut q: Query<(&ActionState<NetInput>, &mut DirectionalInput, &mut Yaw)>,
) {
    for (state, mut dir, mut yaw) in &mut q {
        // DirectionalInput layout matches the single-player combiner: x = strafe,
        // y = jump (0/1), z = forward.
        dir.0 = Vec3::new(
            state.0.move_xz[0],
            if state.0.jump { 1.0 } else { 0.0 },
            state.0.move_xz[1],
        );
        yaw.0 = state.0.yaw;
    }
}

/// Registers the shared protocol. Add to BOTH the client and server apps, AFTER
/// their respective lightyear plugin group.
/// Client→server diagnostics so the dev box's per-version `server.log` carries
/// client-local prediction load. Rollbacks are computed on the client (the server is
/// authoritative and never rolls back), and on wasm the browser console isn't
/// reachable from the build box — so the client periodically reports its cumulative
/// `PredictionMetrics` and the server logs them (`[rb] …`), the same way `[rtt]` is
/// logged server-side. Measurement only; nothing gameplay reads it.
#[derive(Serialize, Deserialize, Clone, Copy, PartialEq, Debug)]
pub struct RollbackReport {
    pub rollbacks: u32,
    pub rollback_ticks: u32,
    /// Largest position divergence (mm) that triggered a rollback this window, and the
    /// number of such triggers — distinguishes movement/sync drift (small) from contact
    /// chaos (large). See `take_rollback_diag`.
    pub max_pos_err_mm: u32,
    pub pos_triggers: u32,
    /// Non-position rollback triggers this window: the count of rotation-divergence
    /// triggers and the largest such divergence (millidegrees). A flight rollback storm
    /// is `pos_triggers ≈ 0` (position quiet) while `rot_triggers` is high — the welded
    /// assembly's part/rider orientations ringing past tolerance. Without this the storm
    /// was invisible in telemetry (only position was reported), which is exactly why the
    /// ride-crash took a full repro to pin down. Linear/angular *velocity* triggers were
    /// measured to be ~always zero during flight, so they're not carried. See
    /// `take_condition_triggers`.
    pub rot_triggers: u32,
    pub max_rot_mdeg: u32,
    /// Client render frame rate ×10 (so one decimal fits a `u16`): the smoothed
    /// (average) FPS and the *worst* single-frame FPS over the recent history buffer.
    /// This is the signal for "the phone's loop is throttling" — a sustained FPS
    /// collapse is what inflates measured RTT/jitter and starves the input timeline
    /// (iOS/WebKit power-governs a sustained-100%-GPU page within seconds). `0` = the
    /// FPS diagnostic wasn't available yet.
    pub fps_x10: u16,
    pub min_fps_x10: u16,
    /// The window's effective render scale factor ×10 (physical/logical pixels).
    /// Confirms the mobile DPR clamp is live: an un-clamped iPhone reports ~30 (3.0×),
    /// the clamp forces ~15 (1.5×). `0` if unavailable.
    pub render_scale_x10: u16,
}

/// TEMPORARY client-crash self-telemetry. A wasm Rust panic aborts silently to the
/// browser console (unreachable from the build box), so the client stashes the panic
/// message in `localStorage` and forwards it here on the next connect; the server logs
/// it (`[panic] …`). Sent on the reliable [`ControlChannel`] so a one-shot crash report
/// isn't dropped. Remove once the freeze is diagnosed.
#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct ClientPanicReport(pub String);

/// Low-rate diagnostics channel. Unreliable: a dropped telemetry sample just means one
/// missing log line, and it must never contend with gameplay traffic for bandwidth.
pub struct TelemetryChannel;

pub struct ProtocolPlugin;

impl Plugin for ProtocolPlugin {
    fn build(&self, app: &mut App) {
        // lightyear builder API (the older `register_component` is
        // deprecated). `.replicate()` marks the component for World replication.
        // Thin slice: replicate the player marker + its transform, server → client.
        app.component::<NetPlayer>().replicate();
        // Avatars replicate Avian `Position`/`Rotation`: predicted on the owning
        // client (so its character is simulated locally with zero input delay and
        // reconciled by rollback against the server) and interpolated on everyone
        // else. `lightyear_avian3d` provides the lerp + the rollback wiring.
        // `add_linear_correction_fn` enables *visual-correction easing*: when a rollback
        // moves the predicted Position/Rotation, the render doesn't snap to the new value
        // — lightyear records the (confirmed − predicted) error and decays it to zero over
        // a few frames (the `CorrectionPolicy` on the PredictionManager), so the body
        // glides into place. Without it, every rollback hard-snaps the pose (and the
        // camera mounted on the predicted character), which is the multiplayer
        // "jumpiness". Measurement (#41) showed the corrections are small (≤~16cm) and
        // frequent — exactly the case easing makes imperceptible. `Position`/`Rotation`
        // are `Diffable<Self>` + `Ease` (avian), and in `AvianReplicationMode::Position`
        // the avian plugin already orders `RollbackSystems::VisualCorrection` after frame
        // interpolation and before the Position→Transform writeback, so this composes with
        // the existing `FrameInterpolate` setup with no further wiring.
        app.component::<Position>()
            .replicate()
            .predict()
            .add_linear_correction_fn::<Position>()
            .with_rollback_condition(position_should_rollback)
            .add_interpolation_with(position_lerp);
        app.component::<Rotation>()
            .replicate()
            .predict()
            .add_linear_correction_fn::<Rotation>()
            .with_rollback_condition(rotation_should_rollback)
            .add_interpolation_with(rotation_lerp);
        // Replicate the bodies' velocities too, predicted alongside Position/Rotation
        // — the canonical lightyear_avian setup for predicted physics. Without these,
        // only *where* a body is gets rolled back, not *how fast it's moving*: a client
        // that starts observing a moving body (a part mid-fall on spawn, or any part a
        // late joiner sees being shoved) rebuilds it at rest, diverges, and the
        // correction smears into a slow drift. Replicating velocity makes the rollback
        // restore the *complete* rigid-body state, so the re-simulation is consistent.
        // Settled/sleeping bodies hold velocity ~0 (unchanged) → no steady-state
        // traffic. (This supersedes the server-side `Settling` spawn-delay hack.)
        app.component::<LinearVelocity>()
            .replicate()
            .predict()
            .with_rollback_condition(linear_velocity_should_rollback)
            .add_interpolation_with(linear_velocity_lerp);
        app.component::<AngularVelocity>()
            .replicate()
            .predict()
            .with_rollback_condition(angular_velocity_should_rollback)
            .add_interpolation_with(angular_velocity_lerp);
        // The part shape is constant, so it only needs replicating (no interp).
        app.component::<NetPart>().replicate();
        app.component::<NetJoint>().replicate();
        // Player-lock welds (see `NetLockJoint`): discrete constraint data each client
        // rebuilds as real predicted physics (like `NetJoint`) — just replicate.
        app.component::<NetLockJoint>().replicate();
        // The per-part membership marker (`InLargestAssembly`) replicates which parts
        // form each room's largest assembly, recomputed on joint create/delete. Clients
        // derive the centre-of-mass orb + combined thrust arrow from it locally over the
        // predicted parts — so the assembly COM is predicted client-side, not streamed.
        // Discrete, so it just needs replicating.
        app.component::<InLargestAssembly>().replicate();
        // Per-room launch/countdown state (see `NetLaunch`), authored on the room's orb
        // entity so every client in the room sees the same countdown and the same
        // blastoff. Discrete, server-authored each frame — just replicate.
        app.component::<NetLaunch>().replicate();
        // Per-room floating-origin frame (see `NetRoomFrame`), authored on the room's
        // orb. Changes every tick while a room flies co-moving (the offset integrates),
        // which is fine — it's one tiny component per room. Just replicate.
        app.component::<NetRoomFrame>().replicate();
        // Held-part hold state (see `NetHold`): replicated so every client can spring a
        // held part toward the holder's hold point instead of predicting it in free-fall.
        app.component::<NetHold>().replicate();
        // Replicate each avatar's facing (`NetFacing`, the server's mirror of its
        // look `Yaw`) so remote clients can draw it facing the way it looks. The body
        // is `ROTATION_LOCKED` at identity (the camera rig owns the look), so facing
        // can't ride on the replicated `Rotation`. This is a *separate* component
        // from the owner's local-input `Yaw` on purpose — replicating `Yaw` itself
        // overwrote the owner's locally-driven look with the round-trip-stale copy
        // and made turning jitter. Interpolated on remotes; the owner never reads it.
        // Predict-synced (not just interpolated) so it reaches the *predicted* remote
        // avatar — every avatar is now `PredictionTarget::All` (see
        // `spawn_player_for_client`); `facing_should_rollback` (see its doc) keeps the
        // every-tick facing change from triggering physics rollbacks. The interpolation
        // fn stays registered as a harmless fallback (nothing is `Interpolated` today).
        app.component::<NetFacing>()
            .replicate()
            .predict()
            .with_rollback_condition(facing_should_rollback)
            .add_interpolation_with(lerp_facing);
        // Whether each avatar's player is pressing move/jump (see `NetMoving`) — the
        // remote-animation signal. Same shape as `NetFacing`: predict-synced so it
        // reaches the predicted remote avatars, never rolls back (cosmetic).
        app.component::<NetMoving>()
            .replicate()
            .predict()
            .with_rollback_condition(moving_should_rollback);
        // The autopilot's attitude PID integral (see `part::AttitudeIntegral`): hidden
        // controller state that steers the burn. It must be REPLICATED, not just predicted
        // — a client that joins or reconnects mid-flight starts its own integral at zero
        // while the server's has already wound up, so the two burns could never converge
        // (measured directly in the tick-aligned burn trace as a steady integral gap).
        // Predict-synced so it reaches the predicted rockets, and — like `NetFacing` — it
        // never *triggers* a rollback itself: it's controller state, so a difference should
        // just update the value, not re-simulate the world (the physics divergence it
        // causes is caught by the Position/Rotation conditions).
        // The thrust-vectoring nozzle deflection (see `part::Gimbal`). Like the PID
        // integral above, the gimbal command is *incremental* — the nozzle IS the control
        // loop's integrator — so it is hidden wound-up state, not a function of the current
        // pose. Unreplicated, a client integrates its own deflection from zero while the
        // server's has already wound up: measured in the per-rocket force trace as a
        // server gimbal of ~3e-3 rad against a client gimbal of ~1e-5 (i.e. zero), which
        // deflects the thrust vector differently on each peer and torques the assembly
        // apart. Replicated + predict-synced, never triggering a rollback itself.
        // The rider's felt-up filter state (see `character::FeltUp`), which drives every
        // avatar's body `Rotation` directly. Replicated so a rollback re-seeds the filter
        // from the server's state and replays it forward; each peer integrates it locally
        // every tick in between, so it is never stale. Never triggers a rollback itself —
        // the rider's `Rotation` is the observable that matters and this rides along with
        // it. (Replicating a smoothed *result* for the client to consume verbatim was the
        // previous design and could not work: the predicted copy refreshed only about
        // every 9 ticks and sat frozen between, so the rider stood up along a staircase of
        // stale directions — the server produced 1861 distinct values across one flight to
        // the client's 216.)
        app.component::<crate::character::FeltUp>()
            .replicate()
            .predict()
            .with_rollback_condition(|_: &crate::character::FeltUp, _: &crate::character::FeltUp| {
                false
            });
        // The escape-cutoff latch (see `part::EscapeCut`): hidden hysteresis state that
        // gates the engines fully on/off, so peers latching on different ticks apply wildly
        // different thrust. Replicated for the same reason as the integral and gimbal — a
        // client that joins after the server latched would otherwise start un-latched.
        app.component::<crate::part::EscapeCut>()
            .replicate()
            .predict()
            .with_rollback_condition(|_: &crate::part::EscapeCut, _: &crate::part::EscapeCut| false);
        app.component::<crate::part::Gimbal>()
            .replicate()
            .predict()
            .with_rollback_condition(|_: &crate::part::Gimbal, _: &crate::part::Gimbal| false);
        app.component::<crate::part::AttitudeIntegral>()
            .replicate()
            .predict()
            .with_rollback_condition(|_: &crate::part::AttitudeIntegral, _: &crate::part::AttitudeIntegral| false);
        // Each player's display name (see `NetName`): replicated so every client can
        // draw it over the avatar and list it in the roster. Changes rarely (only on
        // rename), so it just needs replicating — no interpolation.
        app.component::<NetName>().replicate();

        // Register `NetInput` as a networked native input. `InputPlugin` is
        // role-agnostic: it adds the client input plugin under lightyear's
        // `client` feature and the server one under `server`, so a single
        // registration here wires both binaries (each compiles only its half).
        app.add_plugins(input::native::InputPlugin::<NetInput>::default());

        // Diagnostics channel + client→server rollback telemetry (see `RollbackReport`).
        // BOTH the channel AND the message need `add_direction`: the channel's
        // `add_direction` registers the observer that installs the channel's
        // sender/receiver onto each link's `Transport` (without it, sending fails with
        // `ChannelNotFound`), while the message's `add_direction` registers the
        // `MessageSender`/`MessageReceiver` components. (`InputChannel` does the same.)
        app.add_channel::<TelemetryChannel>(ChannelSettings {
            mode: ChannelMode::UnorderedUnreliable,
            ..default()
        })
        .add_direction(NetworkDirection::ClientToServer);
        // `register_message`, not Bevy's `add_message` (events→messages rename in
        // 0.17 gave `App` its own `add_message`, which would shadow this).
        app.register_message::<RollbackReport>()
            .add_direction(NetworkDirection::ClientToServer);
        // Reliable client→server control channel + the `SetName` rename message on it
        // (same channel-then-message `add_direction` pattern as the telemetry channel;
        // reliable so a rename isn't dropped, sequenced so only the newest wins).
        app.add_channel::<ControlChannel>(ChannelSettings {
            mode: ChannelMode::SequencedReliable(ReliableSettings::default()),
            ..default()
        })
        .add_direction(NetworkDirection::ClientToServer);
        app.register_message::<SetName>()
            .add_direction(NetworkDirection::ClientToServer);
        app.register_message::<SetAvatar>()
            .add_direction(NetworkDirection::ClientToServer);
        app.register_message::<ResetPosition>()
            .add_direction(NetworkDirection::ClientToServer);
        app.register_message::<ResetRoom>()
            .add_direction(NetworkDirection::ClientToServer);
        app.register_message::<SetLocked>()
            .add_direction(NetworkDirection::ClientToServer);
        app.register_message::<RequestLaunch>()
            .add_direction(NetworkDirection::ClientToServer);
        app.register_message::<SaveGame>()
            .add_direction(NetworkDirection::ClientToServer);
        // TEMPORARY client-crash report on the reliable control channel.
        app.register_message::<ClientPanicReport>()
            .add_direction(NetworkDirection::ClientToServer);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use bevy::math::DVec3;

    /// Drift past the trigger parks the anchor at `REBASE_REST_Y` and folds the
    /// shift + boost into the frame.
    #[test]
    fn rebase_triggers_past_the_drift_threshold() {
        let anchor = Vec3::new(0.0, 2500.0, 0.0);
        let velocity = Vec3::new(0.0, 120.0, 0.0);
        let out = rebase_room_frame(DVec3::ZERO, Vec3::ZERO, anchor, velocity).unwrap();
        assert_eq!(out.dpos, Vec3::new(0.0, 2500.0 - REBASE_REST_Y, 0.0));
        assert_eq!(out.dvel, velocity);
        assert_eq!(out.offset, out.dpos.as_dvec3());
        assert_eq!(out.velocity, velocity);
    }

    /// Inside the band nothing happens — including for an active frame still far
    /// from the true origin (no reset flap on the way up).
    #[test]
    fn rebase_holds_inside_the_band() {
        assert!(rebase_room_frame(
            DVec3::ZERO,
            Vec3::ZERO,
            Vec3::new(0.0, 1999.0, 0.0),
            Vec3::Y
        )
        .is_none());
        assert!(rebase_room_frame(
            DVec3::new(0.0, 10_000.0, 0.0),
            Vec3::new(0.0, 50.0, 0.0),
            Vec3::new(0.0, 100.0, 0.0),
            Vec3::Y
        )
        .is_none());
    }

    /// Descending under `REBASE_RESET_M` true lands the frame EXACTLY on zero
    /// (assignment, not accumulated inverse shifts).
    #[test]
    fn rebase_resets_exactly_to_zero_near_the_true_origin() {
        let offset = DVec3::new(0.25, 900.0, -0.5);
        let velocity = Vec3::new(0.0, -30.0, 0.0);
        let out = rebase_room_frame(offset, velocity, Vec3::new(0.0, 50.0, 0.0), Vec3::ZERO)
            .unwrap();
        assert_eq!(out.dpos, -offset.as_vec3());
        assert_eq!(out.dvel, -velocity);
        assert_eq!(out.offset, DVec3::ZERO);
        assert_eq!(out.velocity, Vec3::ZERO);
    }

    /// The countdown must schedule at least its advertised duration — never less, or the
    /// banner is clipped. `TICK` is 16 ms, so 3 s is 187.5 ticks and has to round *up*.
    #[test]
    fn the_countdown_schedule_is_never_short() {
        let scheduled = LAUNCH_COUNTDOWN_TICKS as f32 * TICK.as_secs_f32();
        assert!(
            scheduled >= crate::launch::LAUNCH_COUNTDOWN_SECS,
            "{LAUNCH_COUNTDOWN_TICKS} ticks is only {scheduled} s",
        );
        // ...and not absurdly long: within one tick of the advertised duration.
        assert!(scheduled - crate::launch::LAUNCH_COUNTDOWN_SECS < TICK.as_secs_f32());
    }

    /// Blastoff is decided by comparing ticks, so every peer fires on the *same* tick
    /// rather than when a replicated flag happens to arrive.
    ///
    /// Regression for a fixed ~4-tick late burn on the client: the gate read the
    /// `launched` level, which is replicate-only, so the missed ticks were never
    /// replayed. Note this asserts the client answers `true` **while `launched` is still
    /// false** — the whole point is that the schedule is known in advance.
    #[test]
    fn blastoff_fires_on_the_scheduled_tick_not_when_the_flag_arrives() {
        let scheduled = 1000u32;
        // What a client sees during the countdown: a schedule, and no launch yet.
        let counting = NetLaunch { blastoff_tick: Some(scheduled), launched: false, ..default() };

        assert!(!counting.launched_at(Tick(scheduled - 1)), "fired a tick early");
        assert!(counting.launched_at(Tick(scheduled)), "missed the scheduled tick");
        assert!(counting.launched_at(Tick(scheduled + 4)));

        // The tick counter wraps; the delta is a wrapping i32, so a schedule either side
        // of the wrap still compares correctly (this is the case a plain `>=` gets wrong).
        let wrapped = NetLaunch { blastoff_tick: Some(u32::MAX), launched: false, ..default() };
        assert!(!wrapped.launched_at(Tick(u32::MAX - 1)));
        assert!(wrapped.launched_at(Tick(u32::MAX)));
        assert!(wrapped.launched_at(Tick(0)), "wrapped past the schedule and forgot it");
    }

    /// A world restored from a save that was already in flight has no tick to be exact
    /// about, so it falls back to the replicated level — which is correct there.
    #[test]
    fn an_unscheduled_launch_falls_back_to_the_replicated_level() {
        let restored = NetLaunch { blastoff_tick: None, launched: true, ..default() };
        assert!(restored.launched_at(Tick(0)));
        assert!(restored.launched_at(Tick(9_999)));

        let idle = NetLaunch::default();
        assert!(!idle.launched_at(Tick(9_999)));
    }
}
