//! Multiplayer networking protocol (lightyear).
//!
//! This module defines the *protocol* — the components, channels, and input
//! types the client and server agree on. It deliberately does NOT add
//! lightyear's `ClientPlugins` / `ServerPlugins`: those live in the client and
//! server crates respectively, and lightyear requires the protocol to be
//! registered *after* the relevant plugin group. `ProtocolPlugin` is added by
//! both binaries after their plugin group.
//!
//! Scaffold status: this registers a representative component + channel and
//! defines the per-tick input type, proving the lightyear 0.28 dependency builds
//! into every target (native + wasm). Wiring the live connection, replicating
//! the Avian physics bodies (via `lightyear_avian3d`), and client-side
//! prediction/interpolation come next, where they can be tested on real
//! endpoints.
use core::time::Duration;

use avian3d::prelude::{AngularVelocity, LinearVelocity, Position, Rotation};
use bevy::ecs::entity::{EntityMapper, MapEntities};
use bevy::prelude::*;
use lightyear::prelude::input::native::ActionState;
use lightyear::prelude::*;
use lightyear_avian3d::types::{angular_velocity, linear_velocity, position, rotation};
use serde::{Deserialize, Serialize};

use crate::{DirectionalInput, Yaw};

// Build-time version identity (generated by build.rs). `BS_PROTOCOL_ID` is fed
// into the netcode handshake on both ends so a cross-version client/server pair is
// rejected; `BS_VERSION` is the short git SHA. Both are re-exported here so the
// client and server crates reach them as `bad_spaceship_shared::net::BS_*`.
include!(concat!(env!("OUT_DIR"), "/bs_version.rs"));

/// The simulation tick interval (60 Hz). The client and server must agree on
/// this, so it lives in the shared protocol — both pass it to their lightyear
/// plugin group's `tick_duration`.
pub const TICK: Duration = Duration::from_millis(1000 / 60);

/// Identifies which connected client controls a replicated player entity.
#[derive(Component, Serialize, Deserialize, Clone, Copy, PartialEq, Debug)]
pub struct NetPlayer {
    pub client_id: u64,
}

/// Per-tick client → server **input intent** (not pose). The server runs the
/// authoritative character simulation from this intent (move direction, jump,
/// look angle), so the world is server-authoritative and — once client-side
/// prediction lands — the client predicts the same simulation locally and the
/// server reconciles only on divergence. The grab-ray fields are still sent from
/// the client's camera for now (the server's grab uses them directly); a later
/// phase reconstructs the ray from the simulated character + look angles.
///
/// Sent via lightyear's native-input channel (registered with
/// `InputPlugin::<NetInput>` in `ProtocolPlugin`); native inputs must be
/// `Serialize`/`Deserialize`/`Clone`/`PartialEq`/`Debug`/`Default` + `Reflect` +
/// `MapEntities`.
#[derive(Serialize, Deserialize, Clone, Copy, PartialEq, Debug, Default, Reflect)]
pub struct NetInput {
    /// Look-relative move intent: `[strafe(+right), forward]`, clamped to length 1
    /// (analog magnitude preserved for the touch joystick / gamepad).
    pub move_xz: [f32; 2],
    /// Jump intent this tick.
    pub jump: bool,
    /// Absolute look yaw (radians) — the movement basis and the avatar's facing.
    pub yaw: f32,
    /// Absolute look pitch (radians) — used by the server grab-ray reconstruction
    /// in a later phase (forwarded now to stabilise the protocol).
    pub pitch: f32,
    /// Camera-orbit-center world position — the origin of the grab look-ray.
    pub grab_origin: [f32; 3],
    /// Hold-point world position — where a grabbed part floats to.
    pub hold_target: [f32; 3],
    /// Target orientation for a held part (the orbit-center look basis, plus any
    /// rotate-gesture adjustment), so the held part doesn't tumble.
    pub hold_rotation: [f32; 4],
    /// The client's intent to be holding a part.
    pub grab: bool,
    /// One-shot intent to attach (joint) the held part to whatever it's touching.
    pub attach: bool,
    /// The lobby room code the client is in (the 6-char matchmaker code as raw
    /// bytes, zero-padded; all-zero = no code / default room). Constant for the
    /// session — carried on the already-reliable input channel rather than a
    /// separate connect message, so the server learns each client's room from its
    /// first input and scopes that client's world to it.
    pub room: [u8; 6],
}

// Focus range / look-angle and the held-part spring stiffnesses are defined once
// in `part.rs` (the single-player gameplay tunables) and reused here so the
// multiplayer selection/hold matches single-player exactly.
use crate::part::{
    MAX_INTERACT_ANGLE, MAX_INTERACT_DISTANCE, ORIENTING_STIFFNESS, POSITIONING_STIFFNESS,
};

/// The part the player is most directly looking at (smallest look-angle within
/// range) — the same focus rule as single-player. `look` is the grab ray
/// direction (hold_target − grab_origin). `parts` yields `(entity,
/// world_position)`.
pub fn focused_part(
    origin: Vec3,
    look: Vec3,
    parts: impl Iterator<Item = (Entity, Vec3)>,
) -> Option<Entity> {
    let mut best = None;
    let mut smallest_angle = MAX_INTERACT_ANGLE;
    for (entity, pos) in parts {
        let between = pos - origin;
        if between.length_squared() < MAX_INTERACT_DISTANCE * MAX_INTERACT_DISTANCE {
            let angle = look.angle_between(between);
            if angle < smallest_angle {
                smallest_angle = angle;
                best = Some(entity);
            }
        }
    }
    best
}

/// Critically-damped positioning acceleration that floats a held part to the
/// hold point (matches `position_held_part`'s oscillator). The caller subtracts
/// gravity to cancel the part's weight.
pub fn hold_acceleration(displacement: Vec3, velocity: Vec3) -> Vec3 {
    let damping = 2.0 * POSITIONING_STIFFNESS.sqrt();
    displacement * POSITIONING_STIFFNESS - velocity * damping
}

/// Critically-damped angular acceleration that drives a held part toward its
/// target orientation (matches `orient_held_part`'s oscillator). `rotation_vector`
/// is the axis-angle error (axis · angle) between the target and current rotation.
pub fn orient_acceleration(rotation_vector: Vec3, angular_velocity: Vec3) -> Vec3 {
    let damping = 2.0 * ORIENTING_STIFFNESS.sqrt();
    rotation_vector * ORIENTING_STIFFNESS - angular_velocity * damping
}

// No entities are referenced by `NetInput`, so the mapping is a no-op — but
// the trait is a required bound for native inputs.
impl MapEntities for NetInput {
    fn map_entities<M: EntityMapper>(&mut self, _entity_mapper: &mut M) {}
}

/// Replicated cuboid shape of a part (full extents = 2 × `half_extents`), plus a
/// stable cross-network id. The shape lets a client rebuild the render mesh; the
/// part's live pose rides on the predicted Avian `Position`/`Rotation`. `id` is
/// the server part entity's bits — a *stable* identity (replicated onto both the
/// client's `Confirmed` and `Predicted` copies) that lets the client match a
/// replicated joint's endpoints (`NetJoint`) to the local *predicted* part
/// entities, without depending on lightyear's confirmed→predicted entity mapping.
#[derive(Component, Serialize, Deserialize, Clone, Copy, PartialEq, Debug, Default)]
pub struct NetPart {
    pub half_extents: [f32; 3],
    pub id: u64,
}

/// A replicated joint between two parts. Carries enough to reconstruct the joint
/// as *real predicted physics* on each client: the stable ids (`NetPart::id`) of
/// the two bodies and their body-local (COM-relative) anchors, in the same order
/// the server's `SphericalJoint` uses (`body1`/`anchor1` ↔ `local_anchor1`). The
/// client looks up the matching *predicted* part entities by id and spawns a real
/// Avian `SphericalJoint` between them, so the assembly is held together by the
/// client's own simulation (and survives rollback) — not just rendered. Without
/// this the predicted parts are unconstrained locally and a lifted assembly sags
/// apart, corrected only by replication.
#[derive(Component, Serialize, Deserialize, Clone, Copy, PartialEq, Debug, Default)]
pub struct NetJoint {
    pub body1: u64,
    pub body2: u64,
    pub anchor1: [f32; 3],
    pub anchor2: [f32; 3],
}

/// An avatar's look yaw (radians), replicated **server → other clients** purely so
/// remote avatars can be drawn facing the way they look. Deliberately a *separate*
/// component from the local-input [`Yaw`]: the owner drives its own `Yaw` locally
/// (the camera rig) and must NOT have it overwritten by the server's round-trip-
/// stale copy — replicating `Yaw` itself made the owner's turning jitter/snap back.
/// The server mirrors each avatar's `Yaw` into `NetFacing` (`sync_avatar_facing`);
/// the owner never reads `NetFacing`, so the round-trip copy landing on its
/// predicted entity is inert, while remote (interpolated) clients read it to face
/// the avatar (`face_replicated_players`).
#[derive(Component, Serialize, Deserialize, Clone, Copy, PartialEq, Debug, Default)]
pub struct NetFacing(pub f32);

/// Interpolate a replicated look yaw along the **shortest** angular path, so a
/// wrap across ±π eases smoothly instead of spinning the long way. Used by
/// lightyear's interpolation for remote avatars' `NetFacing` (their facing).
fn lerp_facing(start: NetFacing, other: NetFacing, t: f32) -> NetFacing {
    use core::f32::consts::{PI, TAU};
    let delta = (other.0 - start.0 + PI).rem_euclid(TAU) - PI;
    NetFacing(start.0 + delta * t)
}

/// Roll back on velocity divergence too, but only past a *meaningful* margin — NOT
/// the default exact `PartialEq` (which fires a rollback on a hair of float drift
/// almost every tick → re-sims the whole predicted world every frame → stutter on a
/// single-threaded phone), and NOT never (which lets velocity drift unbounded until
/// it surfaces as a delayed position snap — e.g. coasting to a stop then jumping
/// back, because the client and server decayed momentum slightly differently and
/// nothing re-synced the velocity). A ~0.5 m/s margin ignores steady-motion float
/// noise but catches the larger divergence that builds up across an acceleration or
/// deceleration transition, keeping the coast-to-stop consistent.
const LINEAR_VELOCITY_ROLLBACK_TOLERANCE: f32 = 0.5; // m/s
const ANGULAR_VELOCITY_ROLLBACK_TOLERANCE: f32 = 1.0; // rad/s

fn linear_velocity_should_rollback(confirmed: &LinearVelocity, predicted: &LinearVelocity) -> bool {
    confirmed.0.distance_squared(predicted.0)
        > LINEAR_VELOCITY_ROLLBACK_TOLERANCE * LINEAR_VELOCITY_ROLLBACK_TOLERANCE
}

fn angular_velocity_should_rollback(
    confirmed: &AngularVelocity,
    predicted: &AngularVelocity,
) -> bool {
    confirmed.0.distance_squared(predicted.0)
        > ANGULAR_VELOCITY_ROLLBACK_TOLERANCE * ANGULAR_VELOCITY_ROLLBACK_TOLERANCE
}

/// Only roll back the predicted pose when it diverges from the server's confirmed
/// pose by a *visible* margin — NOT lightyear's default exact `PartialEq`, which
/// fires a full-world rollback on sub-millimeter float drift. The client and server
/// run the same sim but not bit-identically (FP non-determinism across platforms),
/// so an exact check diverges almost every snapshot → a rollback (re-simming the
/// character + every predicted part) nearly every frame → the predicted character
/// and the camera mounted on it judder, reading as a low-frame-rate "roughness".
/// A few-cm / few-degree tolerance lets the client keep its locally-predicted pose
/// for trivial disagreements (still server-authoritative on real divergence — a
/// wall hit, a shove — which exceeds the margin and snaps, eased by visual
/// correction), so prediction stays smooth. Applies to every predicted body
/// (registration is global): the character *and* the loose parts.
const POSITION_ROLLBACK_TOLERANCE: f32 = 0.05; // metres
const ROTATION_ROLLBACK_TOLERANCE: f32 = 0.05; // radians (~3°)

fn position_should_rollback(confirmed: &Position, predicted: &Position) -> bool {
    confirmed.0.distance_squared(predicted.0)
        > POSITION_ROLLBACK_TOLERANCE * POSITION_ROLLBACK_TOLERANCE
}

fn rotation_should_rollback(confirmed: &Rotation, predicted: &Rotation) -> bool {
    confirmed.0.angle_between(predicted.0) > ROTATION_ROLLBACK_TOLERANCE
}

// lightyear's `LerpFn` takes its endpoints by value; `lightyear_avian3d`'s lerps
// take them by reference, so wrap them.
fn position_lerp(start: Position, other: Position, t: f32) -> Position {
    position::lerp(&start, &other, t)
}
fn rotation_lerp(start: Rotation, other: Rotation, t: f32) -> Rotation {
    rotation::lerp(&start, &other, t)
}
fn linear_velocity_lerp(start: LinearVelocity, other: LinearVelocity, t: f32) -> LinearVelocity {
    linear_velocity::lerp(&start, &other, t)
}
fn angular_velocity_lerp(start: AngularVelocity, other: AngularVelocity, t: f32) -> AngularVelocity {
    angular_velocity::lerp(&start, &other, t)
}

/// Bridge a networked avatar's per-tick input *intent* into the movement inputs the
/// shared `walk_based_on_input`/`jump_based_on_input` read — `DirectionalInput`
/// (move + jump) and `Yaw` (look). Runs in `FixedUpdate` *before* `CharacterMovement`
/// on BOTH ends: the server simulates the body authoritatively from intent, and the
/// predicting client replays the same intent through the same systems so rollback
/// reconciles deterministically.
///
/// Deliberately does NOT touch the body's Avian `Rotation`. The body is
/// `ROTATION_LOCKED` and stays at identity, which is what the camera rig relies on:
/// the camera-orbit center is a *child* of the body and applies the full look yaw
/// itself (`mouse_motion`), so writing yaw onto the body too would double the
/// camera's rotation relative to the movement direction. Remote-player *facing* is
/// therefore carried separately (a replicated look angle applied to the rendered
/// avatar), not by spinning the physics body.
pub fn apply_net_input(
    mut q: Query<(&ActionState<NetInput>, &mut DirectionalInput, &mut Yaw)>,
) {
    for (state, mut dir, mut yaw) in &mut q {
        // DirectionalInput layout matches the single-player combiner: x = strafe,
        // y = jump (0/1), z = forward.
        dir.0 = Vec3::new(
            state.0.move_xz[0],
            if state.0.jump { 1.0 } else { 0.0 },
            state.0.move_xz[1],
        );
        yaw.0 = state.0.yaw;
    }
}

/// Registers the shared protocol. Add to BOTH the client and server apps, AFTER
/// their respective lightyear plugin group.
pub struct ProtocolPlugin;

impl Plugin for ProtocolPlugin {
    fn build(&self, app: &mut App) {
        // lightyear builder API (the older `register_component` is
        // deprecated). `.replicate()` marks the component for World replication.
        // Thin slice: replicate the player marker + its transform, server → client.
        app.component::<NetPlayer>().replicate();
        // Avatars replicate Avian `Position`/`Rotation`: predicted on the owning
        // client (so its character is simulated locally with zero input delay and
        // reconciled by rollback against the server) and interpolated on everyone
        // else. `lightyear_avian3d` provides the lerp + the rollback wiring.
        app.component::<Position>()
            .replicate()
            .predict()
            .with_rollback_condition(position_should_rollback)
            .add_interpolation_with(position_lerp);
        app.component::<Rotation>()
            .replicate()
            .predict()
            .with_rollback_condition(rotation_should_rollback)
            .add_interpolation_with(rotation_lerp);
        // Replicate the bodies' velocities too, predicted alongside Position/Rotation
        // — the canonical lightyear_avian setup for predicted physics. Without these,
        // only *where* a body is gets rolled back, not *how fast it's moving*: a client
        // that starts observing a moving body (a part mid-fall on spawn, or any part a
        // late joiner sees being shoved) rebuilds it at rest, diverges, and the
        // correction smears into a slow drift. Replicating velocity makes the rollback
        // restore the *complete* rigid-body state, so the re-simulation is consistent.
        // Settled/sleeping bodies hold velocity ~0 (unchanged) → no steady-state
        // traffic. (This supersedes the server-side `Settling` spawn-delay hack.)
        app.component::<LinearVelocity>()
            .replicate()
            .predict()
            .with_rollback_condition(linear_velocity_should_rollback)
            .add_interpolation_with(linear_velocity_lerp);
        app.component::<AngularVelocity>()
            .replicate()
            .predict()
            .with_rollback_condition(angular_velocity_should_rollback)
            .add_interpolation_with(angular_velocity_lerp);
        // The part shape is constant, so it only needs replicating (no interp).
        app.component::<NetPart>().replicate();
        app.component::<NetJoint>().replicate();
        // Replicate each avatar's facing (`NetFacing`, the server's mirror of its
        // look `Yaw`) so remote clients can draw it facing the way it looks. The body
        // is `ROTATION_LOCKED` at identity (the camera rig owns the look), so facing
        // can't ride on the replicated `Rotation`. This is a *separate* component
        // from the owner's local-input `Yaw` on purpose — replicating `Yaw` itself
        // overwrote the owner's locally-driven look with the round-trip-stale copy
        // and made turning jitter. Interpolated on remotes; the owner never reads it.
        app.component::<NetFacing>()
            .replicate()
            .add_interpolation_with(lerp_facing);

        // Register `NetInput` as a networked native input. `InputPlugin` is
        // role-agnostic: it adds the client input plugin under lightyear's
        // `client` feature and the server one under `server`, so a single
        // registration here wires both binaries (each compiles only its half).
        app.add_plugins(input::native::InputPlugin::<NetInput>::default());
    }
}
